
ui.faces.look_r = "(  ᵔ-ᵔ)"
ui.faces.look_l = "(ᵔ ᵔ  )"
ui.faces.look_r_happy = "(☞ ᵔ³ᵔ)☞"
ui.faces.look_l_happy = "☜(ᵔ°ᵔ ☜)"
ui.faces.sleep = "(-.-)zZ"
ui.faces.sleep2 = "(-o-)z"
ui.faces.awake = "(  ⚆-⚆)"
ui.faces.bored = "╭∩╮(⇀x↼)"
ui.faces.intense = "( ╯°O°)╯"
ui.faces.cool = "( ⌐◉-◉)"
ui.faces.happy = "( ╯◕‿◕)╯"
ui.faces.excited = "(☞ ⚆o⚆)☞"
ui.faces.grateful = "(˘‿˘)♥"
ui.faces.motivated = "(  ⚆o⚆)"
ui.faces.demotivated = "(○-○' )"
ui.faces.smart = "☝(˘-˘ )"
ui.faces.lonely = "( ╥-╥)"
ui.faces.sad = "(≖_≖ )"
ui.faces.angry = "(╯'̀-'́)╯"
ui.faces.friend = "( ᵔ‿ᵔ)♥"
ui.faces.broken = "(.▃▃.)"
ui.faces.debug = "(͡ouO͡)?"
ui.faces.upload = "(  1‿0)"
ui.faces.upload1 = "(  1‿1)"
ui.faces.upload2 = "(  0‿1)"
